-- =====================================================
-- SQL Minor Project : Bike Store Sales & Inventory Analysis
-- Student Name : Meghana Balappa Uppar 
-- Objective : Analyze store sales performance, product demand
-- and stock availability using SQL JOINs and aggregation.
-- =====================================================

CREATE DATABASE BikeStoreProject;
USE BikeStoreProject;
SHOW TABLES;

-- -----------------------------------------------------
-- Task 1 : Store Performance
-- Calculate total revenue generated by each store
-- -----------------------------------------------------

SELECT 
    s.store_name AS Store_Name,
    SUM(oi.list_price * oi.quantity * (1 - oi.discount)) AS Store_Revenue
FROM stores s
INNER JOIN orders o
    ON s.store_id = o.store_id
INNER JOIN order_items oi
    ON o.order_id = oi.order_id
GROUP BY s.store_name
ORDER BY Store_Revenue DESC;

-- -----------------------------------------------------
-- Task 2 : Product Popularity
-- Identify top 5 products based on quantity sold
-- -----------------------------------------------------

SELECT 
    p.product_name AS Product,
    SUM(oi.quantity) AS Total_Units_Sold
FROM products p
INNER JOIN order_items oi
    ON p.product_id = oi.product_id
GROUP BY p.product_name
ORDER BY Total_Units_Sold DESC
LIMIT 5;

-- -----------------------------------------------------
-- Task 3 : Customer Location
-- Show customers and the store from which they placed orders
-- -----------------------------------------------------

SELECT 
    c.first_name,
    c.last_name,
    c.city AS Customer_City,
    s.store_name AS Store_Name
FROM customers c
INNER JOIN orders o
    ON c.customer_id = o.customer_id
INNER JOIN stores s
    ON o.store_id = s.store_id
ORDER BY Store_Name;

-- -----------------------------------------------------
-- Task 4 : Brand Insights
-- Count total products available for each brand
-- -----------------------------------------------------

SELECT 
    b.brand_name AS Brand,
    COUNT(p.product_id) AS Number_of_Products
FROM brands b
INNER JOIN products p
    ON b.brand_id = p.brand_id
GROUP BY b.brand_name
ORDER BY Number_of_Products DESC;

-- -----------------------------------------------------
-- Task 5 : Low Stock Alert
-- Find products that have zero stock in stores
-- -----------------------------------------------------

SELECT 
    p.product_name AS Product,
    s.store_name AS Store,
    st.quantity AS Stock_Quantity
FROM stocks st
INNER JOIN products p
    ON st.product_id = p.product_id
INNER JOIN stores s
    ON st.store_id = s.store_id
WHERE st.quantity = 0
ORDER BY Product;